### ISSUE TITLE
Problème commandes volets RTS

### ISSUE THREAD

**Issue by Chris88140** [redbug26/jeedom-tahoma#34]
Bonjour,
Après avoir installé le plugin Tahoma hier (tous mes fichiers sont à jour),  je n'arrive pas à manoeuvrer tous les volets RTS.
Dans la configuration Jeedom, la communication Tahoma est OK, et j'avais donné l'autorisation à distance de ma box Somfy.
Quand je retourne sur le compte somfy, il redemande l'accès à distance, est-ce normal ?
Voici le rapport d'une commande en erreur.

[2021-01-01 09:20:57][DEBUG] : send command close to rts://1217-6346-3734/16729048
[2021-01-01 09:20:57][DEBUG] : {"label":"close","actions":[{"deviceURL":"rts:\/\/1217-6346-3734\/16729048","commands":[{"name":"close","parameters":[""]}]}]}
[2021-01-01 09:20:57][DEBUG] : send command: {"errorCode":"INCOMPATIBLE_VALUE","error":"close() : Invalid value for command parameter p1 : expected (optional) integer value between 0 and 30 but got "}
[2021-01-01 09:20:57][DEBUG] : return cancelExecutions: ()
[2021-01-01 09:20:57][DEBUG] : set cancelExecutions: ()

D'avance, merci de votre attention et de votre lumière.
Cordialement,

**Comment by madone91** [comment]
bonjour,
exactement le même problème ! @Chris88140 as tu trouvé une solution ? Cdt,

**Comment by Chris88140** [comment]
Bonjour,Non toujours pas.J'ai posé mon cas sur leur site.Le 3 janv. 2021 17:42, madone91 <notifications@github.com> a écrit :

bonjour,

exactement le même problème ! @Chris88140 as tu trouvé une solution ? Cdt,

**Comment by madone91** [comment]
Merci pour ton retourPour info, mon message d’erreur : new cookie - logon: ok: 200[2021-01-03 17:43:11][DEBUG] : send command: {"errorCode":"INCOMPATIBLE_VALUE","error":"open() : Invalid value for command parameter p1 : expected (optional) integer value between 0 and 30 but got "}[2021-01-03 17:43:11][DEBUG] : return cancelExecutions: ()[2021-01-03 17:43:11][DEBUG] : set cancelExecutions: ()[2021-01-03 18:01:28][DEBUG] : send command: ko: 401. Will retry Cdt  Provenance : Courrier pour Windows 10 De : Chris88140Envoyé le :dimanche 3 janvier 2021 18:44À : redbug26/jeedom-tahomaCc : madone91; CommentObjet :Re: [redbug26/jeedom-tahoma] Problème commandes volets RTS (#34) Bonjour,Non toujours pas.J'ai posé mon cas sur leur site.Le 3 janv. 2021 17:42, madone91 <notifications@github.com> a écrit : bonjour, exactement le même problème ! @Chris88140 as tu trouvé une solution ? Cdt, —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Chris88140** [comment]
Bonjour,
J'ai appliqué la procédure suivante mais pareil.
Impossible de manœuvrer les volets avec Jeedom, sauf la touche test qui fait descendre le volet pendant 2-3 secondes.
J'en ai profité pour désinstaller le plugin tahoma et réinstaller, mais pareil, communication tahoma OK, mais pas de contrôle sur les volets.
Une idée svp ?

'Couper l'alim
Appuyer sur reset avec un trombone (celui de droite).
Rester appuyé et remettre l'alim
Attendre 15" que le voyant clignote rouge
Relâcher le bouton reset
Attendre 2mn que le voyant passe au vert.
NE PAS COUPER L'ALIM pendant cette manip.'

**Comment by spottier88** [comment]
Bonjour, idem chez moi (Jeedom V4, acquisition du plugin). 
Les équipements remontent bien dans Jeedom mais seule la fonction "test" fonctionne.

Des nouvelles ???
Merci par avance

**Comment by Chris88140** [comment]
Bonjour spottier88, vosgien également ?
Voici le lien pour y remédier.
https://community.jeedom.com/t/pas-de-controle-sur-volets-rts/48499/2

**Comment by spottier88** [comment]
Oui, Je vois la vie en Vosges :)

Merci pour le lien, j'ai fait la modif et cela fonctionne. 
Merci beaucoup
